country_timezone_map = {
    "Afghanistan": "Asia/Kabul",
    "Albania": "Europe/Tirane",
    "Algeria": "Africa/Algiers",
    "American Samoa": "Pacific/Pago_Pago",
    "Andorra": "Europe/Andorra",
    "Angola": "Africa/Luanda",
    "Anguilla": "America/Anguilla",
    "Antarctica": "Antarctica/McMurdo",
    "Antigua and Barbuda": "America/Antigua",
    "Argentina": "America/Argentina/Buenos_Aires",
    "Armenia": "Asia/Yerevan",
    "Aruba": "America/Aruba",
    "Australia": "Australia/Lord_Howe",
    "Austria": "Europe/Vienna",
    "Azerbaijan": "Asia/Baku",
    "Bahamas": "America/Nassau",
    "Bahrain": "Asia/Bahrain",
    "Bangladesh": "Asia/Dhaka",
    "Barbados": "America/Barbados",
    "Belarus": "Europe/Minsk",
    "Belgium": "Europe/Brussels",
    "Belize": "America/Belize",
    "Benin": "Africa/Porto-Novo",
    "Bermuda": "Atlantic/Bermuda",
    "Bhutan": "Asia/Thimphu",
    "Bolivia, Plurinational State of": "America/La_Paz",
    "Bonaire, Sint Eustatius and Saba": "America/Kralendijk",
    "Bosnia and Herzegovina": "Europe/Sarajevo",
    "Botswana": "Africa/Gaborone",
    "Brazil": "America/Noronha",
    "British Indian Ocean Territory": "Indian/Chagos",
    "Brunei Darussalam": "Asia/Brunei",
    "Bulgaria": "Europe/Sofia",
    "Burkina Faso": "Africa/Ouagadougou",
    "Burundi": "Africa/Bujumbura",
    "Cabo Verde": "Atlantic/Cape_Verde",
    "Cambodia": "Asia/Phnom_Penh",
    "Cameroon": "Africa/Douala",
    "Canada": "America/St_Johns",
    "Cayman Islands": "America/Cayman",
    "Central African Republic": "Africa/Bangui",
    "Chad": "Africa/Ndjamena",
    "Chile": "America/Santiago",
    "China": "Asia/Shanghai",
    "Christmas Island": "Indian/Christmas",
    "Cocos (Keeling) Islands": "Indian/Cocos",
    "Colombia": "America/Bogota",
    "Comoros": "Indian/Comoro",
    "Congo": "Africa/Brazzaville",
    "Congo, The Democratic Republic of the": "Africa/Kinshasa",
    "Cook Islands": "Pacific/Rarotonga",
    "Costa Rica": "America/Costa_Rica",
    "Croatia": "Europe/Zagreb",
    "Cuba": "America/Havana",
    "Cura\u00e7ao": "America/Curacao",
    "Cyprus": "Asia/Nicosia",
    "Czechia": "Europe/Prague",
    "C\u00f4te d'Ivoire": "Africa/Abidjan",
    "Denmark": "Europe/Copenhagen",
    "Djibouti": "Africa/Djibouti",
    "Dominica": "America/Dominica",
    "Dominican Republic": "America/Santo_Domingo",
    "Ecuador": "America/Guayaquil",
    "Egypt": "Africa/Cairo",
    "El Salvador": "America/El_Salvador",
    "Equatorial Guinea": "Africa/Malabo",
    "Eritrea": "Africa/Asmara",
    "Estonia": "Europe/Tallinn",
    "Eswatini": "Africa/Mbabane",
    "Ethiopia": "Africa/Addis_Ababa",
    "Falkland Islands (Malvinas)": "Atlantic/Stanley",
    "Faroe Islands": "Atlantic/Faroe",
    "Fiji": "Pacific/Fiji",
    "Finland": "Europe/Helsinki",
    "France": "Europe/Paris",
    "French Guiana": "America/Cayenne",
    "French Polynesia": "Pacific/Tahiti",
    "French Southern Territories": "Indian/Kerguelen",
    "Gabon": "Africa/Libreville",
    "Gambia": "Africa/Banjul",
    "Georgia": "Asia/Tbilisi",
    "Germany": "Europe/Berlin",
    "Ghana": "Africa/Accra",
    "Gibraltar": "Europe/Gibraltar",
    "Greece": "Europe/Athens",
    "Greenland": "America/Nuuk",
    "Grenada": "America/Grenada",
    "Guadeloupe": "America/Guadeloupe",
    "Guam": "Pacific/Guam",
    "Guatemala": "America/Guatemala",
    "Guernsey": "Europe/Guernsey",
    "Guinea": "Africa/Conakry",
    "Guinea-Bissau": "Africa/Bissau",
    "Guyana": "America/Guyana",
    "Haiti": "America/Port-au-Prince",
    "Holy See (Vatican City State)": "Europe/Vatican",
    "Honduras": "America/Tegucigalpa",
    "Hong Kong": "Asia/Hong_Kong",
    "Hungary": "Europe/Budapest",
    "Iceland": "Atlantic/Reykjavik",
    "India": "Asia/Kolkata",
    "Indonesia": "Asia/Jakarta",
    "Iran, Islamic Republic of": "Asia/Tehran",
    "Iraq": "Asia/Baghdad",
    "Ireland": "Europe/Dublin",
    "Isle of Man": "Europe/Isle_of_Man",
    "Israel": "Asia/Jerusalem",
    "Italy": "Europe/Rome",
    "Jamaica": "America/Jamaica",
    "Japan": "Asia/Tokyo",
    "Jersey": "Europe/Jersey",
    "Jordan": "Asia/Amman",
    "Kazakhstan": "Asia/Almaty",
    "Kenya": "Africa/Nairobi",
    "Kiribati": "Pacific/Tarawa",
    "Korea, Democratic People's Republic of": "Asia/Pyongyang",
    "Korea, Republic of": "Asia/Seoul",
    "Kuwait": "Asia/Kuwait",
    "Kyrgyzstan": "Asia/Bishkek",
    "Lao People's Democratic Republic": "Asia/Vientiane",
    "Latvia": "Europe/Riga",
    "Lebanon": "Asia/Beirut",
    "Lesotho": "Africa/Maseru",
    "Liberia": "Africa/Monrovia",
    "Libya": "Africa/Tripoli",
    "Liechtenstein": "Europe/Vaduz",
    "Lithuania": "Europe/Vilnius",
    "Luxembourg": "Europe/Luxembourg",
    "Macao": "Asia/Macau",
    "Madagascar": "Indian/Antananarivo",
    "Malawi": "Africa/Blantyre",
    "Malaysia": "Asia/Kuala_Lumpur",
    "Maldives": "Indian/Maldives",
    "Mali": "Africa/Bamako",
    "Malta": "Europe/Malta",
    "Marshall Islands": "Pacific/Majuro",
    "Martinique": "America/Martinique",
    "Mauritania": "Africa/Nouakchott",
    "Mauritius": "Indian/Mauritius",
    "Mayotte": "Indian/Mayotte",
    "Mexico": "America/Mexico_City",
    "Micronesia, Federated States of": "Pacific/Chuuk",
    "Moldova, Republic of": "Europe/Chisinau",
    "Monaco": "Europe/Monaco",
    "Mongolia": "Asia/Ulaanbaatar",
    "Montenegro": "Europe/Podgorica",
    "Montserrat": "America/Montserrat",
    "Morocco": "Africa/Casablanca",
    "Mozambique": "Africa/Maputo",
    "Myanmar": "Asia/Yangon",
    "Namibia": "Africa/Windhoek",
    "Nauru": "Pacific/Nauru",
    "Nepal": "Asia/Kathmandu",
    "Netherlands": "Europe/Amsterdam",
    "New Caledonia": "Pacific/Noumea",
    "New Zealand": "Pacific/Auckland",
    "Nicaragua": "America/Managua",
    "Niger": "Africa/Niamey",
    "Nigeria": "Africa/Lagos",
    "Niue": "Pacific/Niue",
    "Norfolk Island": "Pacific/Norfolk",
    "North Macedonia": "Europe/Skopje",
    "Northern Mariana Islands": "Pacific/Saipan",
    "Norway": "Europe/Oslo",
    "Oman": "Asia/Muscat",
    "Pakistan": "Asia/Karachi",
    "Palau": "Pacific/Palau",
    "Palestine, State of": "Asia/Gaza",
    "Panama": "America/Panama",
    "Papua New Guinea": "Pacific/Port_Moresby",
    "Paraguay": "America/Asuncion",
    "Peru": "America/Lima",
    "Philippines": "Asia/Manila",
    "Pitcairn": "Pacific/Pitcairn",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Puerto Rico": "America/Puerto_Rico",
    "Qatar": "Asia/Qatar",
    "Romania": "Europe/Bucharest",
    "Russian Federation": "Europe/Kaliningrad",
    "Rwanda": "Africa/Kigali",
    "R\u00e9union": "Indian/Reunion",
    "Saint Barth\u00e9lemy": "America/St_Barthelemy",
    "Saint Helena, Ascension and Tristan da Cunha": "Atlantic/St_Helena",
    "Saint Kitts and Nevis": "America/St_Kitts",
    "Saint Lucia": "America/St_Lucia",
    "Saint Martin (French part)": "America/Marigot",
    "Saint Pierre and Miquelon": "America/Miquelon",
    "Saint Vincent and the Grenadines": "America/St_Vincent",
    "Samoa": "Pacific/Apia",
    "San Marino": "Europe/San_Marino",
    "Sao Tome and Principe": "Africa/Sao_Tome",
    "Saudi Arabia": "Asia/Riyadh",
    "Senegal": "Africa/Dakar",
    "Serbia": "Europe/Belgrade",
    "Seychelles": "Indian/Mahe",
    "Sierra Leone": "Africa/Freetown",
    "Singapore": "Asia/Singapore",
    "Sint Maarten (Dutch part)": "America/Lower_Princes",
    "Slovakia": "Europe/Bratislava",
    "Slovenia": "Europe/Ljubljana",
    "Solomon Islands": "Pacific/Guadalcanal",
    "Somalia": "Africa/Mogadishu",
    "South Africa": "Africa/Johannesburg",
    "South Georgia and the South Sandwich Islands": "Atlantic/South_Georgia",
    "South Sudan": "Africa/Juba",
    "Spain": "Europe/Madrid",
    "Sri Lanka": "Asia/Colombo",
    "Sudan": "Africa/Khartoum",
    "Suriname": "America/Paramaribo",
    "Svalbard and Jan Mayen": "Arctic/Longyearbyen",
    "Sweden": "Europe/Stockholm",
    "Switzerland": "Europe/Zurich",
    "Syrian Arab Republic": "Asia/Damascus",
    "Taiwan, Province of China": "Asia/Taipei",
    "Tajikistan": "Asia/Dushanbe",
    "Tanzania, United Republic of": "Africa/Dar_es_Salaam",
    "Thailand": "Asia/Bangkok",
    "Timor-Leste": "Asia/Dili",
    "Togo": "Africa/Lome",
    "Tokelau": "Pacific/Fakaofo",
    "Tonga": "Pacific/Tongatapu",
    "Trinidad and Tobago": "America/Port_of_Spain",
    "Tunisia": "Africa/Tunis",
    "Turkey": "Europe/Istanbul",
    "Turkmenistan": "Asia/Ashgabat",
    "Turks and Caicos Islands": "America/Grand_Turk",
    "Tuvalu": "Pacific/Funafuti",
    "Uganda": "Africa/Kampala",
    "Ukraine": "Europe/Simferopol",
    "United Arab Emirates": "Asia/Dubai",
    "United Kingdom": "Europe/London",
    "United States": "America/New_York",
    "United States Minor Outlying Islands": "Pacific/Midway",
    "Uruguay": "America/Montevideo",
    "Uzbekistan": "Asia/Samarkand",
    "Vanuatu": "Pacific/Efate",
    "Venezuela, Bolivarian Republic of": "America/Caracas",
    "Viet Nam": "Asia/Ho_Chi_Minh",
    "Virgin Islands, British": "America/Tortola",
    "Virgin Islands, U.S.": "America/St_Thomas",
    "Wallis and Futuna": "Pacific/Wallis",
    "Western Sahara": "Africa/El_Aaiun",
    "Yemen": "Asia/Aden",
    "Zambia": "Africa/Lusaka",
    "Zimbabwe": "Africa/Harare",
    "\u00c5land Islands": "Europe/Mariehamn"
}